-- Universal Geometry Dash level metadata and download-deduplication tables.
-- Existing Cvolton-compatible `levels` tables are preserved by CREATE TABLE IF NOT EXISTS.

CREATE TABLE IF NOT EXISTS `{{prefix}}levels` (
    `levelID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `levelName` VARCHAR(100) NOT NULL DEFAULT '',
    `gameVersion` INT NOT NULL DEFAULT 0,
    `binaryVersion` INT NOT NULL DEFAULT 0,
    `userName` VARCHAR(20) NOT NULL DEFAULT '',
    `levelDesc` TEXT NOT NULL,
    `levelVersion` INT NOT NULL DEFAULT 1,
    `levelLength` INT NOT NULL DEFAULT 0,
    `audioTrack` INT NOT NULL DEFAULT 0,
    `auto` TINYINT NOT NULL DEFAULT 0,
    `password` VARCHAR(32) NOT NULL DEFAULT '0',
    `original` INT NOT NULL DEFAULT 0,
    `twoPlayer` TINYINT NOT NULL DEFAULT 0,
    `songID` INT NOT NULL DEFAULT 0,
    `objects` INT NOT NULL DEFAULT 0,
    `coins` INT NOT NULL DEFAULT 0,
    `requestedStars` INT NOT NULL DEFAULT 0,
    `extraString` TEXT NOT NULL,
    `levelString` MEDIUMTEXT NOT NULL,
    `levelInfo` TEXT NOT NULL,
    `secret` VARCHAR(64) NOT NULL DEFAULT '',
    `uploadDate` BIGINT NOT NULL DEFAULT 0,
    `updateDate` BIGINT NOT NULL DEFAULT 0,
    `userID` INT UNSIGNED NOT NULL DEFAULT 0,
    `extID` VARCHAR(100) NOT NULL DEFAULT '0',
    `unlisted` TINYINT NOT NULL DEFAULT 0,
    `unlisted2` TINYINT NOT NULL DEFAULT 0,
    `hostname` VARCHAR(45) NOT NULL DEFAULT '',
    `isLDM` TINYINT NOT NULL DEFAULT 0,
    `wt` INT NOT NULL DEFAULT 0,
    `wt2` INT NOT NULL DEFAULT 0,
    `settingsString` TEXT NOT NULL,
    `songIDs` TEXT NOT NULL,
    `sfxIDs` TEXT NOT NULL,
    `ts` BIGINT NOT NULL DEFAULT 0,
    `starDifficulty` INT NOT NULL DEFAULT 0,
    `downloads` BIGINT NOT NULL DEFAULT 0,
    `likes` BIGINT NOT NULL DEFAULT 0,
    `starDemon` TINYINT NOT NULL DEFAULT 0,
    `starDemonDiff` INT NOT NULL DEFAULT 0,
    `starAuto` TINYINT NOT NULL DEFAULT 0,
    `starStars` INT NOT NULL DEFAULT 0,
    `starFeatured` INT NOT NULL DEFAULT 0,
    `starEpic` INT NOT NULL DEFAULT 0,
    `starCoins` TINYINT NOT NULL DEFAULT 0,
    `rateDate` BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (`levelID`),
    KEY `idx_levels_user` (`userID`),
    KEY `idx_levels_extid` (`extID`),
    KEY `idx_levels_upload` (`uploadDate`),
    KEY `idx_levels_likes` (`likes`),
    KEY `idx_levels_downloads` (`downloads`),
    KEY `idx_levels_stars` (`starStars`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `{{prefix}}core_level_downloads` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `levelID` INT UNSIGNED NOT NULL,
    `ipHash` CHAR(64) NOT NULL,
    `downloadedAt` BIGINT NOT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_core_level_downloads_level_ip` (`levelID`, `ipHash`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
